/************
 * DO NOT COPY THIS FILE TO YOUR ENVIROMENT. THIS IS AN EXAMPLE. THIS FILE SHOULD COME FROM YOUR IMPLEMENTATION.
 */

#include "csgp_config.h"

#ifndef CSGP_SUPPORTED_H
#define CSGP_SUPPORTED_H

#define CSGP_SUPPORTED 0
#define CSGP_SUPPORTED_INPUT CSGP_INPUT_KEYBOARD | CSGP_INPUT_KEYBOARD_MOUSE | CSGP_INPUT_MOUSE

#endif
