#ifndef CSGP_CONFIG_H
#define CSGP_CONFIG_H

#define CSGP_CONFIG_MULTI_WINDOW 0b1
#define CSGP_CONFIG_AUDIO 0b10

#define CSGP_INPUT_CONTROLLER 0b1
#define CSGP_INPUT_KEYBOARD 0b10
#define CSGP_INPUT_TOUCH 0b100
#define CSGP_INPUT_MOUSE 0b1000
#define CSGP_INPUT_KEYBOARD_MOUSE 0b10000

#endif
